version: '3.9'
services:
  server:
    container_name: lang-dictionary-server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
      - '5432:5432'
    env_file:
      - .env
